Initialize CVS branch OPENBSD_2_6
The per-file CVS branch roots do not exactly match a reconstructed source-branch commit.

diff --git a/regress/sys/kern/unfdpass/Makefile b/regress/sys/kern/unfdpass/Makefile
--- a/regress/sys/kern/unfdpass/Makefile
+++ b/regress/sys/kern/unfdpass/Makefile
@@ -1,25 +1,16 @@
-#	$OpenBSD: Makefile,v 1.10 2011/07/06 19:48:10 matthew Exp $
 #	$NetBSD: Makefile,v 1.3 1998/03/02 21:57:38 cgd Exp $
 
 PROG=	unfdpass
+NOMAN=	noman, no way, man
 
-CLEANFILES+=file1 file2 file3 output test-sock
-REGRESS_TARGETS=do-unfdpass1 do-unfdpass2 do-unfdpass3 do-unfdpass4
+CLEANFILES+=file1 file2 output test-sock
 
-do-unfdpass1: ${PROG}
-	./unfdpass > output
-	cmp -s ${.CURDIR}/expected output
+regress:
+	@./unfdpass > output
+	@if ! cmp -s ${.CURDIR}/expected output; then \
+		echo "FAILED"; \
+	else \
+		echo "PASSED"; \
+	fi
 
-do-unfdpass2: ${PROG}
-	./unfdpass -p > output
-	cmp -s ${.CURDIR}/expected output
-
-do-unfdpass3: ${PROG}
-	./unfdpass -q > output
-	cmp -s ${.CURDIR}/expected output
-
-do-unfdpass4: ${PROG}
-	./unfdpass -pq > output
-	cmp -s ${.CURDIR}/expected output
-
-.include <bsd.regress.mk>
+.include <bsd.prog.mk>
